# Generated by Django 3.0.7 on 2020-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
