# Generated by Django 3.0.7 on 2020-07-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
